### ISSUE TITLE
componentについて

### ISSUE THREAD

**Issue by taikikku0314** [jjj999/pisat#2]
get_component()メゾッドで受け取れるcomponent一覧みたいなのはありますか？

**Comment by jjj999** [comment]
そのような一覧はありません．なぜなら Component であればどれでも取得できるからです．Component を受け取れるかどうかは，ユーザーが ComponentGroup にどのような Component を登録するかに依ります．

*get_component* メソッドは ComponentGroup で実装されているメソッドで，ComponentGroup 内に登録されている Component を呼び出すことができるメソッドです（登録は *append* メソッドで行えます）．つまり，ComponentGroup を継承している ComponentManager などのオブジェクトでは，内部に登録してある Component であればどれでも取得できます．もし，どのクラスが Component であるのかを知りたい場合は調べたいクラスの継承元を辿ってみてください．
