### ISSUE TITLE
sample_counter.pyでCanSatクラスをinstantiateする際に、dloggerを渡さないとエラーになる件

### ISSUE THREAD

**Issue by jnskkmhr** [jjj999/pisat#3]
CanSatクラスをdloggerを渡さないで、contextとcomponent_mangerだけでinstantiateすると、
`AttributeError: 'NoneType' object has no attribute 'set_model'`
とエラーが出ます。
CanSatクラスのコンストラクタ内で`self._dlogger.set_model(self._node.model)`(line120)を呼び出す際に、`self.dlogger=None`であるためにAttributeErrorが出るのだと思われます。CanSatクラスを使用する際には、dloggerを引数に入れないと避けられないエラーですか？

**Comment by jjj999** [comment]
普通にバグだと思います．

```python
if self._dlogger:
            self._dlogger.set_model(self._node.model)
```

のようにするべきですね．issue#3 ブランチで修正したので確認してみてください．

**Comment by jnskkmhr** [comment]
ありがとうございます。確認しました。同様に、runメソッドの部分でも、上のような修正が必要だと思います。`self._dlogger.set_model(self._node.model)`, `self._dlogger.close()`の部分ということです。

**Comment by jjj999** [comment]
そうですね．修正しておきました．

**Comment by jjj999** [comment]
pisat には昨年の NSE の直前に製作していたということもあり，このような不完全な検証によるバグがいくつかあります．現在ゆっくりではありますが v0.1.0 の開発を行っていて，v0.0.0 のコードのリファクタリングとナビゲーション（v0.0.0 では CanSat クラスによる状態管理）をメインに行っています（v0.1.0 は v0.0.0 に破壊的な変更を行います）．一人でやるとかなり時間と労力がかかるので，他のコラボレータを募集しているのですが，もしフレームワークの開発に興味があれば <jjj999to@gmail.com> まで連絡ください．

**Comment by jnskkmhr** [comment]
分かりました。考えておきます。
